### ISSUE TITLE
Problem with library

### ISSUE THREAD

**Issue by Anna781938** [ggravlingen/pyesef#569]
Good afternoon
First, I would like to thank you for your efforts in developing the library pyesef. It is very useful for research and financial analysis.
I work as a researcher in the field of accounting and would to use the library to extract financial data and then build ML models. Unfortunately, I have problems as the library does not work on my computer
Below please find the enclosed Anaconda prompt
I installed Anaconda C:\Users\User

(base) C:\Users\User>pip install pyesef
Requirement already satisfied: pyesef in c:\users\user\anaconda3\lib\site-packages (1.0.2)

(base) C:\Users\User>python3 pyesef -e
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\pyesef\__main__.py", line 4, in <module>
    from pyesef import __version__
ModuleNotFoundError: No module named 'pyesef'

(base) C:\Users\User>

Please let me know, what is wrong
Thank you very much in advance
BR
Anna Karmańska

**Comment by ggravlingen** [comment]
Hi,

This sounds like an issue with your environment. You seem to be running windows, have you tried installing docker and vscode? This library runs as a containerized dev environment if you want it to.

**Comment by Anna781938** [comment]
Hi,
Thank you for your reply. I have installed VS code. Now, it is a problem importing 'MutableSet' from 'collections'. 
ImportError: cannot import name 'MutableSet' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)

**Comment by ggravlingen** [comment]
You are running on Python 3.10 and this library requires Python 3.11 or higher. Try installing a more recent version of Python.

**Comment by Anna781938** [comment]
I have Python 3.11.7
Maybe the problem is that MutableSet should be imported from collections.abc instead of collection?
https://docs.python.org/3.9/library/collections.abc.html?highlight=abc%20collections#module-collections.abc

The full track is: 
(base) C:\Users\User>python3 -m pyesef -e
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\pyesef\__main__.py", line 6, in <module>
    from pyesef.helpers.read_and_save_filings import read_and_save_filings
  File "C:\Users\User\pyesef\helpers\read_and_save_filings.py", line 8, in <module>
    from arelle import FileSource as FileSourceFile, PluginManager
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\arelle\FileSource.py", line 9, in <module>
    from arelle import XmlUtil
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\arelle\XmlUtil.py", line 13, in <module>
    from arelle.XbrlConst import ixbrlAll, qnLinkFootnote, xhtml, xml, xsd, xhtml
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\arelle\XbrlConst.py", line 1, in <module>
    from arelle.ModelValue import qname
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\arelle\ModelValue.py", line 7, in <module>
    from arelle import PythonUtil # define 2.x or 3.x string types
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\arelle\PythonUtil.py", line 9, in <module>
    from collections import OrderedDict, MutableSet
ImportError: cannot import name 'MutableSet' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)

(base) C:\Users\User>

**Comment by ggravlingen** [comment]
Thank you for the full stack trace!

The problem does not arise in this library (`pyesef`). `MutableSet` is imported in the library `Arelle`, which is the actual library extracting the XBRL data in the reported documents.

The library works, as shown here in my local instance just now:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/b685f8d3-e3ad-499a-9391-a0a9335168b4">

Your best bet is to run this in VSCode using a containerized environment as this will save you the hassle of setting up all dependencies. Please have a look at [this guide](https://code.visualstudio.com/docs/devcontainers/tutorial).
